from building import *
Import('RTT_ROOT')
Import('rtconfig')

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('ports/easyflash', src, depend = ['PKG_USING_EASYFLASH'], CPPPATH = CPPPATH)

Return('group')
